In [4]:
import pandas as pd

In [2]:
import sqlalchemy

#server is down, so no worries (this credentials will fail, use yours)
username = 'postgres'
password = '20qD6jdSfRUQuRdwnDuj'
host_name = 'containers-us-west-20.railway.app'
port = 8047
db_name = 'railway'

conn_str = 'postgresql://{}:{}@{}:{}/{}'.format(username, password, host_name, port, db_name)
engine = sqlalchemy.create_engine(conn_str)
query = 'SELECT * FROM prediction;'

In [5]:
data_server = pd.read_sql_query(query, engine)

In [6]:
data_server

,id,observation_id,observation,prediction,proba,true_class
0,63,e7ab1073-5193-4ec6-aa07-efb0bc97acbb,"{""observation_id"": ""e7ab1073-5193-4ec6-aa07-ef...",0.0,0.096773,0
1,66,34b142db-63a2-42ee-89a4-e553051ab933,"{""observation_id"": ""34b142db-63a2-42ee-89a4-e5...",0.0,0.094996,0
2,69,af500e60-b8b2-404c-b1e5-25ce9b00556b,"{""observation_id"": ""af500e60-b8b2-404c-b1e5-25...",0.0,0.137928,0
3,72,ba106e8c-fb22-42de-a80d-9b0564964c75,"{""observation_id"": ""ba106e8c-fb22-42de-a80d-9b...",0.0,0.179262,0
4,75,9e8783a9-8377-448f-8882-d4b2f352187a,"{""observation_id"": ""9e8783a9-8377-448f-8882-d4...",0.0,0.096773,0
...,...,...,...,...,...,...
4015,3991,dec81b01-b351-4030-b419-6044c91cd895,"{""observation_id"": ""dec81b01-b351-4030-b419-60...",0.0,0.307740,0
4016,4007,9c7e363f-26df-4b8a-92cf-b3cbf70827cc,"{""observation_id"": ""9c7e363f-26df-4b8a-92cf-b3...",1.0,0.846658,0
4017,4023,b08e103a-4f94-48c6-974f-1b746dde4ca0,"{""observation_id"": ""b08e103a-4f94-48c6-974f-1b...",1.0,0.548129,0
4018,4039,493b76ae-8e5e-498d-8a9d-68eeeb8d51de,"{""observation_id"": ""493b76ae-8e5e-498d-8a9d-68...",1.0,0.515709,0
4019,4055,6ad11ac4-59c3-4989-a8ba-583847799548,"{""observation_id"": ""6ad11ac4-59c3-4989-a8ba-58...",1.0,0.587626,0

In [7]:
data_server.to_csv('../data/trial1.csv')